// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LithumeBmsSamwoo

#include "ui.h"

void btnPackChange(lv_event_t * e)
{
	// Your code here
}

void btnEventPack1(lv_event_t * e)
{
	// Your code here
}

void btnEventPack2(lv_event_t * e)
{
	// Your code here
}

void btnEventPack3(lv_event_t * e)
{
	// Your code here
}

void btnEventPack4(lv_event_t * e)
{
	// Your code here
}

void btnEventPack5(lv_event_t * e)
{
	// Your code here
}

void btnEventPack6(lv_event_t * e)
{
	// Your code here
}

void btnEventPack7(lv_event_t * e)
{
	// Your code here
}

void btnEventPack8(lv_event_t * e)
{
	// Your code here
}

void saveButtenEvent(lv_event_t * e)
{
	// Your code here
}
