// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LithumeBmsSamwoo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btnPackChange(lv_event_t * e);
void btnEventPack1(lv_event_t * e);
void btnEventPack2(lv_event_t * e);
void btnEventPack3(lv_event_t * e);
void btnEventPack4(lv_event_t * e);
void btnEventPack5(lv_event_t * e);
void btnEventPack6(lv_event_t * e);
void btnEventPack7(lv_event_t * e);
void btnEventPack8(lv_event_t * e);
void saveButtenEvent(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
